### ISSUE TITLE
voting project test : Cannot read properties of undefined

### ISSUE THREAD

**Issue by cxp-13** [solana-developers/developer-bootcamp-2024#5]
```
import * as anchor from '@coral-xyz/anchor'
import { Program } from '@coral-xyz/anchor'
import { Keypair, PublicKey } from '@solana/web3.js'
import { Votingdapp2 } from '../target/types/votingdapp2'
// import '@types/jest';

import { startAnchor } from "solana-bankrun";
import { BankrunProvider } from "anchor-bankrun";
import { it } from 'node:test';

const IDL = require('../target/idl/votingdapp2.json')

const votingAddress = new PublicKey("AsjZ3kWAUSQRNt2pZVeJkywhZ6gpLpHZmJjduPmKZDZZ");

describe('votingdapp2', () => {

  let context;
  let provider;
  let votingProgram: Program<Votingdapp2>;

  beforeAll(async () => {
    context = await startAnchor("", [{ name: "votingdapp2", programId: votingAddress }], []);
    provider = new BankrunProvider(context);
    votingProgram = new Program<Votingdapp2>(
      IDL,
      provider
    );
  })

  it('Initialize Poll', async () => {
    console.log("votingProgram", votingProgram);
    

    await votingProgram.methods.initializePoll(
      new anchor.BN(1),
      "What is your favorite color?",
      new anchor.BN(0),
      new anchor.BN(1728810858),
    ).rpc();

    const [pollAddress] = PublicKey.findProgramAddressSync([new anchor.BN(1).toArrayLike(Buffer, 'le', 8)], votingAddress);
    const poll = await votingProgram.account.poll.fetch(pollAddress);
    console.log(poll);
  })
  ```
  when I try to execute `anchor test`:
  ```
  test at tests/votingdapp2.spec.ts:53:24
✖ Initialize Poll (4.236166ms)
  TypeError: Cannot read properties of undefined (reading 'methods')
      at /home/cxp/solana_learn/2024_solana_tutorial/voting-dapp-2/anchor/tests/votingdapp2.spec.ts:34:25
      at Generator.next (<anonymous>)
      at /home/cxp/solana_learn/2024_solana_tutorial/voting-dapp-2/anchor/tests/votingdapp2.spec.ts:31:71
      at new Promise (<anonymous>)
      at Object.<anonymous>.__awaiter (/home/cxp/solana_learn/2024_solana_tutorial/voting-dapp-2/anchor/tests/votingdapp2.spec.ts:27:12)
      at TestContext.<anonymous> (/home/cxp/solana_learn/2024_solana_tutorial/voting-dapp-2/anchor/tests/votingdapp2.spec.ts:30:36)
      at Test.runInAsyncScope (node:async_hooks:211:14)
      at Test.run (node:internal/test_runner/test:887:25)
      at Test.start (node:internal/test_runner/test:786:17)
      at startSubtestAfterBootstrap (node:internal/test_runner/harness:280:17)
      at processTicksAndRejections (node:internal/process/task_queues:105:5)
```

and I log the `votingProgram` is undefine.

**Comment by jacobcreech** [comment]
Are you positive the IDL exists and the program is deployed to your public key that you stated?

**Comment by rayvego** [comment]
Apparently, solana-create-dapp doesn't create a node app inside anchor folder so you'll have to `npm init` inside anchor and the dependencies should look like this

```
"dependencies": {
    "@coral-xyz/anchor": "^0.30.0",
    "@solana/web3.js": "1.91.9",
    "anchor-bankrun": "^0.4.0",
    "solana-bankrun": "^0.2.0"
  },
"devDependencies": {
    "@types/chai": "^5.0.0",
    "@types/jest": "^29.5.13",
    "@types/mocha": "^10.0.9",
    "jest": "^29.7.0",
    "ts-node": "^10.9.2",
    "typescript": "^5.6.3"
  }
```

Also, make sure to add `poll.description = poll_description;` in your lib.rs in the initialize_poll function. The instructor hadn't mentioned this in the video but seems like he added it.

**Comment by rayvego** [comment]
Also, make sure you set up your tsconfig correctly!
/anchor/tsconfig.json
```
{
  "extends": "../tsconfig.json",
  "compilerOptions": {
    "types": ["node", "jest"],
    "typeRoots": ["./node_modules/@types"],
    "lib": ["es2015"],
    "target": "es6",
    "resolveJsonModule": true,
    "allowSyntheticDefaultImports": true,
    "esModuleInterop": true
  }
}
```

Just for ref, these are my files:

lib.rs:
```
use anchor_lang::prelude::*;

declare_id!("");

pub const ANCHOR_DISCRIMINATOR_SIZE: usize = 8;

#[program]
pub mod voting {
    use super::*;

    pub fn initialize_poll(
        ctx: Context<InitializePoll>,
        poll_id: u64,
        poll_description: String,
        poll_start: u64,
        poll_end: u64,
    ) -> Result<()> {
        let poll = &mut ctx.accounts.poll;
        poll.poll_id = poll_id;
        poll.description = poll_description;
        poll.poll_start = poll_start;
        poll.poll_end = poll_end;
        poll.candidate_amount = 0;

        Ok(())
    }

    pub fn initialize_candidate(
        ctx: Context<InitializeCandidate>,
        candidate_name: String,
        _poll_id: u64,
    ) -> Result<()> {
        let poll = &mut ctx.accounts.poll;
        poll.candidate_amount += 1;
        let candidate = &mut ctx.accounts.candidate;
        candidate.candidate_name = candidate_name;
        candidate.candidate_votes = 0;

        Ok(())
    }

    pub fn vote(ctx: Context<Vote>, _candidate_name: String, _poll_id: u64) -> Result<()> {
        let candidate = &mut ctx.accounts.candidate;
        candidate.candidate_votes += 1;

        Ok(())
    }
}

#[derive(Accounts)]
#[instruction(candidate_name: String, poll_id: u64)]
pub struct Vote<'info> {
    pub signer: Signer<'info>,

    #[account(
        mut, // this is very important to mention because even if you console log above in the vote function, it will say that you have voted and the count has increased and it won't give an error
        // by default all accounts are immutable so in order to actually update the vote count, you'll need to mention mut!
        seeds = [poll_id.to_le_bytes().as_ref(), candidate_name.as_bytes()],
        bump
    )]
    pub poll: Account<'info, Poll>,

    pub candidate: Account<'info, Candidate>,
}

#[derive(Accounts)]
#[instruction(poll_id: u64)] // this annotation tells Anchor that this instruction expects an additional argument (in this case, poll_id: u64) to be passed when the transaction is submitted
                             // it is an input argument for calling the transaction
pub struct InitializePoll<'info> {
    #[account(mut)]
    pub signer: Signer<'info>,

    #[account(
        init,
        payer = signer,
        space = ANCHOR_DISCRIMINATOR_SIZE + Poll::INIT_SPACE,
        seeds = [poll_id.to_le_bytes().as_ref()], // this is different than b"poll_id"
        // poll_id.to_le_bytes() converts a numeric value (like a u64) into its little-endian byte array representation. This is dynamic, as it depends on the actual numeric value of poll_id.
        // b"poll_id" is a byte string representing the literal string "poll_id", and its byte representation is &[u8]. This means that b"poll_id" would always resolve to the byte array equivalent of the characters "poll_id".
        bump,
    )]
    pub poll: Account<'info, Poll>,

    pub system_program: Program<'info, System>,
}

#[derive(Accounts)]
#[instruction(candidate_name: String, poll_id: u64)] // make sure the order of parameters here are in the same order as above in the instruction handler initialize_candidate
pub struct InitializeCandidate<'info> {
    #[account(mut)]
    pub signer: Signer<'info>,

    #[account(
        mut, // again, you need to update the poll account every time a new candidate is added so mention mut!
        seeds = [poll_id.to_le_bytes().as_ref()],
        bump
    )]
    pub poll: Account<'info, Poll>,

    #[account(
        init,
        payer = signer,
        space = ANCHOR_DISCRIMINATOR_SIZE + Candidate::INIT_SPACE,
        seeds = [poll_id.to_le_bytes().as_ref(), candidate_name.as_bytes()], // whats the difference between to_le_bytes and as_bytes
        bump,
    )]
    pub candidate: Account<'info, Candidate>,

    pub system_program: Program<'info, System>,
}

#[account]
#[derive(InitSpace)]
pub struct Candidate {
    #[max_len(32)]
    pub candidate_name: String,
    pub candidate_votes: u64,
}

#[account]
#[derive(InitSpace)]
pub struct Poll {
    pub poll_id: u64,

    #[max_len(200)]
    pub description: String,

    pub poll_start: u64,
    pub poll_end: u64,
    pub candidate_amount: u64,
}
```

and voting.spec.ts:
```
import {PublicKey} from "@solana/web3.js";
import {startAnchor} from "solana-bankrun";
import {Voting} from "../target/types/voting"
import {Program} from "@coral-xyz/anchor";
import {BankrunProvider} from "anchor-bankrun";
import * as anchor from "@coral-xyz/anchor";

const IDL = require("../target/idl/voting.json")

const votingAddress = new PublicKey("")

describe("Voting", () => {
    it("Initialize Poll", async () => {
        const context = await startAnchor("", [{name: "voting", programId: votingAddress}], [])
        const provider = new BankrunProvider(context)

        const votingProgram = new Program<Voting>(IDL, provider)

        await votingProgram.methods.initializePoll(
            new anchor.BN(1),
            "What is your favorite type of peanut butter?",
            new anchor.BN(0),
            new anchor.BN(1821246480),
        ).rpc()
    })
})
```

**Comment by PrateekSavanur** [comment]
Please remove the line 

`import { it } from 'node:test';` 

from your tests file i.e. line 9.

It conflicts with the framework that we are using for testing
